version: '3'
services:
  postgresql:
    image: postgres:11.3
    ports:
    - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ''
    volumes:
    - postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis:4.0-alpine
    ports:
      - "6379:6379"

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
    volumes:
      - .:/bank-eleven
    env_file:
      - .env

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/bank-eleven
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
      - sidekiq
    env_file:
      - .env

volumes:
  postgresql_data:
